# Generated by Django 2.1.5 on 2019-01-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('size', models.PositiveIntegerField()),
                ('site', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('school', models.ForeignKey(on_delete='CASCADE', related_name='students', to='basic_app.School')),
            ],
        ),
    ]
